-- SQL requests for XAMS (http://www.xams.org)
-- by Stephane LECLERC <sleclerc@actionweb.fr>
-- 
-- // read data queries
-- $rcmail_config['vacation_sql_read'] =
--         array("SELECT pm_users.AutoReplySubject AS vacation_subject, " .
--                 "pm_users.AutoReplyText AS vacation_message, " .
--                 "pm_users.AutoReply AS vacation_enable " .
--                 "FROM xams.pm_sites " .
--                 "INNER JOIN xams.pm_domains ON pm_sites.id = pm_domains.siteid" .
--                 "INNER JOIN xams.pm_users ON pm_sites.id = pm_users.siteid " .
--                 "WHERE pm_users.name = %email_local AND pm_domains.name = %email_domain;"
--         );
--
-- // write data queries
-- $rcmail_config['vacation_sql_write'] =
--         array("UPDATE xams.pm_users " .
--                 "INNER JOIN xams.pm_sites ON pm_sites.id = pm_users.siteid " .
--                 "INNER JOIN xams.pm_domains ON pm_sites.id = pm_domains.siteid" .
--                 "SET pm_users.AutoReplySubject = %vacation_subject, " .
--                 "pm_users.AutoReplyText = %vacation_message, " .
--                 "pm_users.AutoReply = %vacation_enable " .
--                 "WHERE pm_users.name = %email_local AND pm_domains.name = %email_domain;"
--         );