<?php

$labels = array();
$labels['vacation'] = 'Dovolená';
$labels['vacationenable'] = 'Zapnuto';
$labels['vacationsubject'] = 'Předmět:';
$labels['vacationmessage'] = 'Zpráva:';
$labels['vacationforwarder'] = 'Přesměrovat na:';
$labels['vacationstart'] = 'Začátek:';
$labels['vacationend'] = 'Konec:';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Zvolte prosím datum začátku.';
$messages['vacationinvalidenddate'] = 'Zvolte prosím datum konce.';
$messages['vacationinvaliddateinterval'] = 'Zadejte platný rozsah datumů.';
$messages['vacationnosubject'] = 'Zadejte prosím předmět automatické odpovědi.';
$messages['vacationnomessage'] = 'Zadejte prosím tělo automatické odpovědi.';
$messages['vacationinvalidforwarder'] = 'Adresa pro přesměrování není platná.';
$messages['vacationinvalidforwarders'] = 'Seznam adres pro přesměrování není platný.';
$messages['vacationdriverdefaulterror'] = 'Unknown execution error';
$messages['vacationdriverconnecterror'] = 'Chyba během připojování';
$messages['vacationdriverprocesserror'] = 'Chyba během zpracovávání';
