<?php

$labels = array();
$labels['vacation'] = 'Vacation';
$labels['vacationenable'] = 'Enable';
$labels['vacationsubject'] = 'Subject:';
$labels['vacationmessage'] = 'Message:';
$labels['vacationforwarder'] = 'Forward address:';

$messages = array();
$messages['vacationnosubject'] = 'Please fill the subject of your vacation.';
$messages['vacationnomessage'] = 'Please fill the message of your vacation.';
$messages['vacationinvalidforwarder'] = 'Please provide a valid forward address.';
$messages['vacationdriverdefaulterror'] = 'Unknown execution error';
$messages['vacationdriverconnecterror'] = 'Error during connection';
$messages['vacationdriverprocesserror'] = 'Error during processing';
?>
