<?php

$labels['vacation'] = 'Vacaciones';
$labels['vacationenable'] = 'Activo';
$labels['vacationsubject'] = 'Asunto:';
$labels['vacationmessage'] = 'Mensaje:';
$labels['vacationforwarder'] = 'Dirección de respuesta:';
$labels['vacationstart'] = 'Fecha Inicio:';
$labels['vacationend'] = 'Fecha Fin:';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Por favor, seleccione una fecha de inicio valida.';
$messages['vacationinvalidenddate'] = 'Por favor, seleccione una fecha de fin valida.';
$messages['vacationnosubject'] = 'Por favor, rellena el asunto de vacaciones.';
$messages['vacationnomessage'] = 'Por favor, rellena el mensaje de vacaciones.';
$messages['vacationinvalidforwarder'] = 'The forward address is not valid.';
$messages['vacationinvalidforwarders'] = 'The forward addresses list is not valid.';
$messages['vacationdriverdefaulterror'] = 'Error de ejecución desconocido';
$messages['vacationdriverconnecterror'] = 'Error durante la conexión';
$messages['vacationdriverprocesserror'] = 'Error durante el proceso';
