<?php

$labels = array();
$labels['vacation'] = 'Vacaciones';
$labels['vacationenable'] = 'Activado';
$labels['vacationsubject'] = 'Asunto:';
$labels['vacationmessage'] = 'Mensaje:';

$messages = array();
$messages['vacationnosubject'] = 'Por favor, escribe un asunto para tus vacaciones.';
$messages['vacationnomessage'] = 'Por favor, escribe un mensaje para tus vacaciones.';
$messages['vacationdriverdefaulterror'] = 'Error desconocido.';
$messages['vacationdriverconnecterror'] = 'Error durante la conexion.';
$messages['vacationdriverprocesserror'] = 'Error en el proceso.';
