<?php

$labels = array();
$labels['vacation'] = 'Répondeur';
$labels['vacationenable'] = 'Activer';
$labels['vacationsubject'] = 'Sujet :';
$labels['vacationmessage'] = 'Message :';
$labels['vacationforwarder'] = 'Adresse de redirection : ';

$messages = array();
$messages['vacationnosubject'] = 'Veuillez saisir le sujet de votre répondeur.';
$messages['vacationnomessage'] = 'Veuillez saisir le message de votre répondeur.';
$messages['vacationinvalidforwarder'] = 'Veuillez fournir une adresse de redirection valide.';
$messages['vacationdriverdefaulterror'] = 'Erreur d\'exécution non spécifiée';
$messages['vacationdriverconnecterror'] = 'Erreur de connexion';
$messages['vacationdriverprocesserror'] = 'Erreur de traitement';
?>

