<?php

$labels = array();
$labels['vacation'] = 'Répondeur';
$labels['vacationenable'] = 'Activer';
$labels['vacationsubject'] = 'Sujet :';
$labels['vacationmessage'] = 'Message :';
$labels['vacationforwarder'] = 'Adresse de redirection :';
$labels['vacationstart'] = 'Début :';
$labels['vacationend'] = 'Fin :';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Veuillez saisir une date de début valide.';
$messages['vacationinvalidenddate'] = 'Veuillez saisir une date de fin valide.';
$messages['vacationinvaliddateinterval'] = 'L\'intervalle de date défini n\'est pas valide.';
$messages['vacationnosubject'] = 'Veuillez saisir le sujet de votre répondeur.';
$messages['vacationnomessage'] = 'Veuillez saisir le message de votre répondeur.';
$messages['vacationinvalidforwarder'] = 'L\'adresse de redirection n\'est pas valide.';
$messages['vacationinvalidforwarders'] = 'La liste d\'adresses de redirection n\'est pas valide.';
$messages['vacationdriverdefaulterror'] = 'Erreur d\'exécution non spécifiée';
$messages['vacationdriverconnecterror'] = 'Erreur de connexion';
$messages['vacationdriverprocesserror'] = 'Erreur de traitement';
