<?php

$labels = array();
$labels['vacation'] = 'Répondeur';
$labels['vacationenable'] = 'Activer';
$labels['vacationsubject'] = 'Sujet:';
$labels['vacationmessage'] = 'Message:';

$messages = array();
$messages['vacationnosubject'] = 'Veuillez saisir le sujet de votre répondeur.';
$messages['vacationnomessage'] = 'Veuillez saisir le message de votre répondeur.';
$messages['vacationdriverdefaulterror'] = 'Erreur d\'exécution non spécifiée';
$messages['vacationdriverconnecterror'] = 'Erreur de connexion';
$messages['vacationdriverprocesserror'] = 'Erreur de traitement';
?>