<?php

$labels = array();
$labels['vacation'] = 'Szabadság';
$labels['vacationenable'] = 'Engedélyezés';
$labels['vacationsubject'] = 'Tárgy:';
$labels['vacationmessage'] = 'Üzenet:';
$labels['vacationforwarder'] = 'Továbbítás:';
$labels['vacationstart'] = 'Kezdete:';
$labels['vacationend'] = 'Vége:';
$labels['vacationkeepcopyininbox'] = 'Másolat megtartása';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Kérem válasszon egy érvényes kezdete dátumot.';
$messages['vacationinvalidenddate'] = 'Kérem válasszon egy érvényes vége dátumot.';
$messages['vacationinvaliddateinterval'] = 'Az időtartam nem érvényes.';
$messages['vacationnosubject'] = 'Kérem adja meg a szabadságüzenet tárgyát.';
$messages['vacationnomessage'] = 'Kérem adja meg a szabadságüzenet törzsét.';
$messages['vacationinvalidforwarder'] = 'A továbbító cím nem érvényes.';
$messages['vacationinvalidforwarders'] = 'A továbbító címek listája nem érvényes.';
$messages['vacationdriverdefaulterror'] = 'Ismeretlen végrehajtási hiba';
$messages['vacationdriverconnecterror'] = 'Hiba a kapcsolódás során';
$messages['vacationdriverprocesserror'] = 'Hiba a feldolgozás során';

