<?php
/*
* Italian translation of rc-vacation
* @author Alessandro De Zorzi - <lota@nonlontano.it>
*/

$labels = array();
$labels['vacation'] = 'Vacation';
$labels['vacationenable'] = 'Attiva';
$labels['vacationsubject'] = 'Oggetto:';
$labels['vacationmessage'] = 'Messaggio:';
$labels['vacationforwarder'] = 'Indirizzo Forward:';
$labels['vacationstart'] = 'Inizio:';
$labels['vacationend'] = 'Fine:';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Seleziona una data di inizio valida.';
$messages['vacationinvalidenddate'] = 'Seleziona una data di fine valida.';
$messages['vacationinvaliddateinterval'] = 'L\'intervallo di date non è valido.';
$messages['vacationnosubject'] = 'Completa il campo oggetto del vacation, grazie.';
$messages['vacationnomessage'] = 'Completa il campo messaggio del vacation, grazie.';
$messages['vacationinvalidforwarder'] = 'L\'indirizzo di forward non è valido.';
$messages['vacationinvalidforwarders'] = 'La lista degli indirizzi di forward non è valida.';
$messages['vacationdriverdefaulterror'] = 'Errore di esecuzione sconosciuto';
$messages['vacationdriverconnecterror'] = 'Errore durante la connessione';
$messages['vacationdriverprocesserror'] = 'Errore durante l\'elaborazione';
