<?php

$labels = array();
$labels['vacation'] = 'Vakantie';
$labels['vacationenable'] = 'Activeer';
$labels['vacationsubject'] = 'Onderwerp:';
$labels['vacationmessage'] = 'Bericht:';
$labels['vacationforwarder'] = 'Doorstuur adres:';
$labels['vacationstart'] = 'Begin:';
$labels['vacationend'] = 'Einde:';
$labels['vacationkeepcopyininbox'] = 'Hou een kopie in Postvak IN';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Gelieve een geldig begin datum te kiezen';
$messages['vacationinvalidenddate'] = 'Gelieve een geldig eind datum te kiezen';
$messages['vacationinvaliddateinterval'] = 'Het tijdsinterval is niet geldig.';
$messages['vacationnosubject'] = 'Gelieve het onderwerp van je vakantie in te vullen.';
$messages['vacationnomessage'] = 'Gelieve het bericht van je vakantie in te vullen.';
$messages['vacationinvalidforwarder'] = 'Het doorstuur adres is niet geldig.';
$messages['vacationinvalidforwarders'] = 'De doorstuur adreslijst is niet geldig.';
$messages['vacationdriverdefaulterror'] = 'Onbekende uitvoerfout';
$messages['vacationdriverconnecterror'] = 'Fout bij het verbinden';
$messages['vacationdriverprocesserror'] = 'Fout bij het verwerken';
