<?php

$labels = array();
$labels['vacation'] = 'Vacanță';
$labels['vacationenable'] = 'Activare';
$labels['vacationsubject'] = 'Subiect:';
$labels['vacationmessage'] = 'Mesaj:';
$labels['vacationforwarder'] = 'Redirecționare la:';
$labels['vacationstart'] = 'Început:';
$labels['vacationend'] = 'Sfârșit:';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Vă rog selectați o dată de început validă.';
$messages['vacationinvalidenddate'] = 'Vă rog selectați o dată de sfârșit validă.';
$messages['vacationinvaliddateinterval'] = 'Intervalul de timp nu este valid.';
$messages['vacationnosubject'] = 'Vă rog completați subiectul mesajului automat.';
$messages['vacationnomessage'] = 'Vă rog completați mesajul automat.';
$messages['vacationinvalidforwarder'] = 'Adresa de redirecționare nu este validă.';
$messages['vacationinvalidforwarders'] = 'Lista de adrese de redirecționare nu este validă.';
$messages['vacationdriverdefaulterror'] = 'Eroare necunoscută la execuție';
$messages['vacationdriverconnecterror'] = 'Eroare la conectare';
$messages['vacationdriverprocesserror'] = 'Eroare la procesare';
