<?php

$labels = array();
$labels['vacation'] = 'Semestersvar';
$labels['vacationenable'] = 'Aktivera';
$labels['vacationsubject'] = 'Ämne:';
$labels['vacationmessage'] = 'Meddelande:';
$labels['vacationforwarder'] = 'Vidarebefodringsadress:';
$labels['vacationstart'] = 'Start:';
$labels['vacationend'] = 'Slut:';
$labels['vacationkeepcopyininbox'] = 'Spara kopia';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Välj ett giltigt startdatum.';
$messages['vacationinvalidenddate'] = 'Välj ett giltigt slutdatum..';
$messages['vacationinvaliddateinterval'] = 'Tidsintervallet felaktigt.';
$messages['vacationnosubject'] = 'Fyll i ämnesraden.';
$messages['vacationnomessage'] = 'Fyll i meddelande.';
$messages['vacationinvalidforwarder'] = 'Ogiltig vidarebefodringsaddress.';
$messages['vacationinvalidforwarders'] = 'Vidarebefodringsaddresslistan ogiltig.';
$messages['vacationdriverdefaulterror'] = 'Okänt fel';
$messages['vacationdriverconnecterror'] = 'Anslutningsfel';
$messages['vacationdriverprocesserror'] = 'Okänt fel';
$messages['vacationdriverdateerror'] = 'Ogiltigt datum, välj ett annat slutdatum';
